version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
        name: install dependencies
        command: |
          bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
        name: Build phase
        command: |
          bundle exec middleman build

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
