version: 2
jobs:
  deploy:
    docker:
      - image: cicleci/ruby:2.4.1-node-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - run:
        name: install dependencies
        command: |
          bundle install --path vendor/bundle

      - run:
        name: Build
        command: |
          bundle exec middleman build

workflows: 
  version: 2
  build_repo:
    jobs:
      - deploy:
        filters:
          branches:
            only: master
